name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install
    
    - name: Install dependencies
      run: npm ci
      env:
        NODE_ENV: development
    - name: Fix Jest Permissions
      run: chmod +x ./node_modules/.bin/jest
    
    - name: Run tests
      run: npm test
    
    - name: Create distribution package
      run: |
        mkdir -p dist
        cp index.js dist/
        cp package.json dist/
        cp package-lock.json dist/
        npm prune --production
        cp -r node_modules dist/
    
    - name: Compress distribution package
      run: |
        cd dist
        zip -r ../app-release.zip .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-package
        path: app-release.zip